### ISSUE TITLE
我也想要docker😁

### ISSUE THREAD

**Issue by 2328760190** [kkkunny/HuggingChatAPI#3]

**Comment by kkkunny** [comment]
项目目录下有Dockerfile文件，直接自己构建即可
`docker build -t HuggingChatAPI:latest .`
`docker run -d --name HuggingChat -p 5695:80 HuggingChatAPI:latest`

**Comment by 2328760190** [comment]
谢谢你

在 2024-10-25 19:16:04，kkkunny ***@***.***> 写道：


项目目录下有Dockerfile文件，直接自己构建即可
docker build -t HuggingChatAPI:latest .
docker run -d --name HuggingChat -p 5695:80 HuggingChatAPI:latest

**Comment by 2328760190** [comment]
docker build的名字要小写哦😁
