### ISSUE TITLE
报错500，本人小白，望大佬指点

### ISSUE THREAD

**Issue by 2328760190** [kkkunny/HuggingChatAPI#4]
平台:koyeb，免费计划，dockerfile构建，端口80，已提取创建过对话，链接:https://controversial-fleur-2328760190-5f6414a0.koyeb.app/
日志:Instance created. Preparing to start...
 KEYWORD | 2024-10-26 15:06:39 | /app/main.go:25 | listen http: 0.0.0.0:80
Instance is starting... Waiting for health checks to pass.
Instance is healthy. All health checks are passing.
   INFO  | 2024-10-26 15:07:35 | /app/main.go:17 | Method [GET] 10.250.92.2:14022 --> /v1/models
   INFO  | 2024-10-26 15:08:13 | /app/main.go:17 | Method [GET] 10.250.92.2:32768 --> /v1/models
   INFO  | 2024-10-26 15:08:23 | /app/main.go:17 | Method [POST] 10.250.92.2:23804 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:08:24 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:09:05 | /app/main.go:17 | Method [POST] 10.250.92.3:15374 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:09:05 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:09:05 | /app/main.go:17 | Method [POST] 10.250.92.2:14022 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:09:06 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:09:06 | /app/main.go:17 | Method [POST] 10.250.92.10:21650 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:09:06 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:09:06 | /app/main.go:17 | Method [POST] 10.250.92.3:15374 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:09:06 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:10:08 | /app/main.go:17 | Method [POST] 10.250.92.3:15374 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:10:08 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:10:41 | /app/main.go:17 | Method [GET] 10.250.92.2:10056 --> /v1/models
   INFO  | 2024-10-26 15:11:24 | /app/main.go:17 | Method [POST] 10.250.92.3:63318 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:11:24 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:11:27 | /app/main.go:17 | Method [POST] 10.250.92.2:23804 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:11:27 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:11:28 | /app/main.go:17 | Method [POST] 10.250.92.10:19880 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:11:28 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:11:29 | /app/main.go:17 | Method [POST] 10.250.92.3:63318 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:11:29 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:11:29 | /app/main.go:17 | Method [POST] 10.250.92.2:23804 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:11:29 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:11:29 | /app/main.go:17 | Method [POST] 10.250.92.3:63318 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:11:29 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:11:29 | /app/main.go:17 | Method [POST] 10.250.92.10:21650 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:11:30 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:11:30 | /app/main.go:17 | Method [POST] 10.250.92.3:15374 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:11:30 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:11:59 | /app/main.go:17 | Method [POST] 10.250.92.2:23804 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:11:59 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:13:10 | /app/main.go:17 | Method [POST] 10.250.92.10:19880 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:13:10 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:13:14 | /app/main.go:17 | Method [POST] 10.250.92.10:19880 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:13:14 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:13:14 | /app/main.go:17 | Method [POST] 10.250.92.3:63318 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:13:15 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:13:15 | /app/main.go:17 | Method [POST] 10.250.92.2:23804 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:13:45 | /app/handler/chat_completions.go:94 | http error: code=504, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94
   INFO  | 2024-10-26 15:13:45 | /app/main.go:17 | Method [POST] 10.250.92.3:15374 --> /v1/chat/completions
  ERROR  | 2024-10-26 15:13:45 | /app/handler/chat_completions.go:94 | http error: code=500, status=
	/usr/local/go/src/net/http/server.go:3137
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90
	/usr/local/go/src/net/http/server.go:2166
	/app/main.go:18
	/usr/local/go/src/net/http/server.go:2166
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459
	/usr/local/go/src/net/http/server.go:2166
	/app/handler/chat_completions.go:94

**Comment by 2328760190** [comment]
自己构建的也这样

**Comment by kkkunny** [comment]
已修复，拉master最新commit就可以了

**Comment by 2328760190** [comment]
谢谢大佬
