### ISSUE TITLE
接口挂了

### ISSUE THREAD

**Issue by iougemini** [kkkunny/HuggingChatAPI#6]
自部署的和demo的接口都挂了

**Comment by kkkunny** [comment]
官方改了列出会话接口的结构，已经修复了

**Comment by millerhuaers** [comment]
镜像没有更新，佬

**Comment by kkkunny** [comment]
> 镜像没有更新，佬

已更新，kkkunny/hugging-chat-api:latest

**Comment by millerhuaers** [comment]
> > 镜像没有更新，佬
> 
> 已更新，kkkunny/hugging-chat-api:latest

谢谢啊。佬
